export const modalData = [
    {
        id: "add__officer__mdt",
        title: "Ajouter un officier au rooter",
        descrip: "",
        enableButtons: true,
        enableSearchBar: true,
        enableAgentCard: true,
        enableMap: false,
        titlePlaceHolder: "Rechercher un officier",
        textBouton: "Ajouter",
        classButton: "button modify addOfficier"
    },
    {
        id: "add__vehicle__mdt",
        title: "Ajouter un véhiculer au rooter",
        descrip: "",
        enableButtons: true,
        enableSearchBar: true,
        enableAgentCard: false,
        enableVehicleCard: true,
        enableMap: false,
        enableTextArea: false,
    },
    {
        id: "edit__agenda__id",
        title: "Modifier l'ordre du jour",
        descrip: "",
        enableButtons: true,
        enableTextArea: true,
        enableSearchBar: false,
        enableAgentCard: false,
        enableVehicleCard: false,
        enableMap: false,
    },
    {
        id: "call_verif",
        title: "Répondre à un appel 911",
        descrip: "Êtes-vous sûr de vouloir prendre cet appel ?",
        enableButtons: true,
        enableMap: false,
        textBouton: "Prendre l'appel",
    },
    {
        id: "call_delete",
        title: "Supprimer un appel",
        descrip: "Êtes vous sûr de supprimer cet appel 911 ?",
        enableButtons: true,
        enableMap: false,
        textBouton: "Supprimer un appel",
        classButton: "button delete"
    },
    {
        id: "call_localisation",
        title: "Localiser un appel",
        descrip: "",
        enableButtons: false,
        enableMap: true,
    },
    {
        id: "view__location__patrouille",
        title: "Localisation",
        descrip: "",
        enableButtons: false,
        enableMap: true,
        enableAgentCard: false
    },
];